version: '3.8'

services:
  diabit-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: diabit_container
    ports:
      - "3030:3030"
    volumes:
      - ./data:/app/data
    environment:
      - PORT=3030
    restart: always
